# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 13:57
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('tag', models.CharField(max_length=10, verbose_name='标签')),
                ('describe', models.CharField(max_length=255, verbose_name='描述')),
                ('logo', models.ImageField(upload_to='img/%Y/%m', verbose_name='服务对象logo')),
                ('image', models.ImageField(upload_to='img/%Y/%m', verbose_name='案例图片')),
                ('context', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('click_count', models.IntegerField(default=0, verbose_name='点击数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Category', verbose_name='文章分类')),
            ],
            options={
                'verbose_name_plural': '服务案例',
                'verbose_name': '服务案例',
            },
        ),
    ]
